services:
  midjourney:
    build: .
    container_name: midjourney
    volumes:
      - ./sqlite:/usr/src/app/sqlite

  caddy:
    image: caddy:2.8.4
    container_name: caddy
    depends_on:
      - "midjourney"
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
      - caddy_data:/data
      - caddy_config:/config

volumes:
  caddy_data:
  caddy_config:
